[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

# Disable Netlify Asset Optimization post-processing which can interfere with Emotion/Theme UI SSR styles
[build.processing]
  # Some accounts support skip_processing. Keep it here for compatibility.
  skip_processing = true

# Be explicit for all processors to ensure nothing is altered at deploy time
[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = false
